// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: chunkserver.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChunkServerService_ReadChunk_FullMethodName      = "/api.ChunkServerService/ReadChunk"
	ChunkServerService_WriteChunk_FullMethodName     = "/api.ChunkServerService/WriteChunk"
	ChunkServerService_ReplicateChunk_FullMethodName = "/api.ChunkServerService/ReplicateChunk"
)

// ChunkServerServiceClient is the client API for ChunkServerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChunkServerServiceClient interface {
	ReadChunk(ctx context.Context, in *ReadChunkRequest, opts ...grpc.CallOption) (*ReadChunkResponse, error)
	WriteChunk(ctx context.Context, in *WriteChunkRequest, opts ...grpc.CallOption) (*WriteChunkResponse, error)
	ReplicateChunk(ctx context.Context, in *ReplicateChunkRequest, opts ...grpc.CallOption) (*ReplicateChunkResponse, error)
}

type chunkServerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChunkServerServiceClient(cc grpc.ClientConnInterface) ChunkServerServiceClient {
	return &chunkServerServiceClient{cc}
}

func (c *chunkServerServiceClient) ReadChunk(ctx context.Context, in *ReadChunkRequest, opts ...grpc.CallOption) (*ReadChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadChunkResponse)
	err := c.cc.Invoke(ctx, ChunkServerService_ReadChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chunkServerServiceClient) WriteChunk(ctx context.Context, in *WriteChunkRequest, opts ...grpc.CallOption) (*WriteChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteChunkResponse)
	err := c.cc.Invoke(ctx, ChunkServerService_WriteChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chunkServerServiceClient) ReplicateChunk(ctx context.Context, in *ReplicateChunkRequest, opts ...grpc.CallOption) (*ReplicateChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplicateChunkResponse)
	err := c.cc.Invoke(ctx, ChunkServerService_ReplicateChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChunkServerServiceServer is the server API for ChunkServerService service.
// All implementations must embed UnimplementedChunkServerServiceServer
// for forward compatibility.
type ChunkServerServiceServer interface {
	ReadChunk(context.Context, *ReadChunkRequest) (*ReadChunkResponse, error)
	WriteChunk(context.Context, *WriteChunkRequest) (*WriteChunkResponse, error)
	ReplicateChunk(context.Context, *ReplicateChunkRequest) (*ReplicateChunkResponse, error)
	mustEmbedUnimplementedChunkServerServiceServer()
}

// UnimplementedChunkServerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChunkServerServiceServer struct{}

func (UnimplementedChunkServerServiceServer) ReadChunk(context.Context, *ReadChunkRequest) (*ReadChunkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadChunk not implemented")
}
func (UnimplementedChunkServerServiceServer) WriteChunk(context.Context, *WriteChunkRequest) (*WriteChunkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteChunk not implemented")
}
func (UnimplementedChunkServerServiceServer) ReplicateChunk(context.Context, *ReplicateChunkRequest) (*ReplicateChunkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReplicateChunk not implemented")
}
func (UnimplementedChunkServerServiceServer) mustEmbedUnimplementedChunkServerServiceServer() {}
func (UnimplementedChunkServerServiceServer) testEmbeddedByValue()                            {}

// UnsafeChunkServerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChunkServerServiceServer will
// result in compilation errors.
type UnsafeChunkServerServiceServer interface {
	mustEmbedUnimplementedChunkServerServiceServer()
}

func RegisterChunkServerServiceServer(s grpc.ServiceRegistrar, srv ChunkServerServiceServer) {
	// If the following call panics, it indicates UnimplementedChunkServerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChunkServerService_ServiceDesc, srv)
}

func _ChunkServerService_ReadChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkServerServiceServer).ReadChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkServerService_ReadChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkServerServiceServer).ReadChunk(ctx, req.(*ReadChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChunkServerService_WriteChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkServerServiceServer).WriteChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkServerService_WriteChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkServerServiceServer).WriteChunk(ctx, req.(*WriteChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChunkServerService_ReplicateChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicateChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkServerServiceServer).ReplicateChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkServerService_ReplicateChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkServerServiceServer).ReplicateChunk(ctx, req.(*ReplicateChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChunkServerService_ServiceDesc is the grpc.ServiceDesc for ChunkServerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChunkServerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.ChunkServerService",
	HandlerType: (*ChunkServerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadChunk",
			Handler:    _ChunkServerService_ReadChunk_Handler,
		},
		{
			MethodName: "WriteChunk",
			Handler:    _ChunkServerService_WriteChunk_Handler,
		},
		{
			MethodName: "ReplicateChunk",
			Handler:    _ChunkServerService_ReplicateChunk_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chunkserver.proto",
}
