// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: chunkserver.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReadChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Length        int64                  `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadChunkRequest) Reset() {
	*x = ReadChunkRequest{}
	mi := &file_chunkserver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadChunkRequest) ProtoMessage() {}

func (x *ReadChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chunkserver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadChunkRequest.ProtoReflect.Descriptor instead.
func (*ReadChunkRequest) Descriptor() ([]byte, []int) {
	return file_chunkserver_proto_rawDescGZIP(), []int{0}
}

func (x *ReadChunkRequest) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *ReadChunkRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadChunkRequest) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

type ReadChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=api.Status" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadChunkResponse) Reset() {
	*x = ReadChunkResponse{}
	mi := &file_chunkserver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadChunkResponse) ProtoMessage() {}

func (x *ReadChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chunkserver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadChunkResponse.ProtoReflect.Descriptor instead.
func (*ReadChunkResponse) Descriptor() ([]byte, []int) {
	return file_chunkserver_proto_rawDescGZIP(), []int{1}
}

func (x *ReadChunkResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OK
}

func (x *ReadChunkResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ReadChunkResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteChunkRequest) Reset() {
	*x = WriteChunkRequest{}
	mi := &file_chunkserver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteChunkRequest) ProtoMessage() {}

func (x *WriteChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chunkserver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteChunkRequest.ProtoReflect.Descriptor instead.
func (*WriteChunkRequest) Descriptor() ([]byte, []int) {
	return file_chunkserver_proto_rawDescGZIP(), []int{2}
}

func (x *WriteChunkRequest) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *WriteChunkRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *WriteChunkRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=api.Status" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteChunkResponse) Reset() {
	*x = WriteChunkResponse{}
	mi := &file_chunkserver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteChunkResponse) ProtoMessage() {}

func (x *WriteChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chunkserver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteChunkResponse.ProtoReflect.Descriptor instead.
func (*WriteChunkResponse) Descriptor() ([]byte, []int) {
	return file_chunkserver_proto_rawDescGZIP(), []int{3}
}

func (x *WriteChunkResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OK
}

func (x *WriteChunkResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ReplicateChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	SourceAddress string                 `protobuf:"bytes,2,opt,name=source_address,json=sourceAddress,proto3" json:"source_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateChunkRequest) Reset() {
	*x = ReplicateChunkRequest{}
	mi := &file_chunkserver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateChunkRequest) ProtoMessage() {}

func (x *ReplicateChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chunkserver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateChunkRequest.ProtoReflect.Descriptor instead.
func (*ReplicateChunkRequest) Descriptor() ([]byte, []int) {
	return file_chunkserver_proto_rawDescGZIP(), []int{4}
}

func (x *ReplicateChunkRequest) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *ReplicateChunkRequest) GetSourceAddress() string {
	if x != nil {
		return x.SourceAddress
	}
	return ""
}

type ReplicateChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=api.Status" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateChunkResponse) Reset() {
	*x = ReplicateChunkResponse{}
	mi := &file_chunkserver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateChunkResponse) ProtoMessage() {}

func (x *ReplicateChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chunkserver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateChunkResponse.ProtoReflect.Descriptor instead.
func (*ReplicateChunkResponse) Descriptor() ([]byte, []int) {
	return file_chunkserver_proto_rawDescGZIP(), []int{5}
}

func (x *ReplicateChunkResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OK
}

func (x *ReplicateChunkResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_chunkserver_proto protoreflect.FileDescriptor

const file_chunkserver_proto_rawDesc = "" +
	"\n" +
	"\x11chunkserver.proto\x12\x03api\x1a\fcommon.proto\"]\n" +
	"\x10ReadChunkRequest\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x03R\x06length\"q\n" +
	"\x11ReadChunkResponse\x12#\n" +
	"\x06status\x18\x01 \x01(\x0e2\v.api.StatusR\x06status\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"Z\n" +
	"\x11WriteChunkRequest\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"^\n" +
	"\x12WriteChunkResponse\x12#\n" +
	"\x06status\x18\x01 \x01(\x0e2\v.api.StatusR\x06status\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"Y\n" +
	"\x15ReplicateChunkRequest\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12%\n" +
	"\x0esource_address\x18\x02 \x01(\tR\rsourceAddress\"b\n" +
	"\x16ReplicateChunkResponse\x12#\n" +
	"\x06status\x18\x01 \x01(\x0e2\v.api.StatusR\x06status\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage2\xda\x01\n" +
	"\x12ChunkServerService\x12:\n" +
	"\tReadChunk\x12\x15.api.ReadChunkRequest\x1a\x16.api.ReadChunkResponse\x12=\n" +
	"\n" +
	"WriteChunk\x12\x16.api.WriteChunkRequest\x1a\x17.api.WriteChunkResponse\x12I\n" +
	"\x0eReplicateChunk\x12\x1a.api.ReplicateChunkRequest\x1a\x1b.api.ReplicateChunkResponseB\x1fZ\x1dgithub.com/Yakshith15/GFS/apib\x06proto3"

var (
	file_chunkserver_proto_rawDescOnce sync.Once
	file_chunkserver_proto_rawDescData []byte
)

func file_chunkserver_proto_rawDescGZIP() []byte {
	file_chunkserver_proto_rawDescOnce.Do(func() {
		file_chunkserver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chunkserver_proto_rawDesc), len(file_chunkserver_proto_rawDesc)))
	})
	return file_chunkserver_proto_rawDescData
}

var file_chunkserver_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_chunkserver_proto_goTypes = []any{
	(*ReadChunkRequest)(nil),       // 0: api.ReadChunkRequest
	(*ReadChunkResponse)(nil),      // 1: api.ReadChunkResponse
	(*WriteChunkRequest)(nil),      // 2: api.WriteChunkRequest
	(*WriteChunkResponse)(nil),     // 3: api.WriteChunkResponse
	(*ReplicateChunkRequest)(nil),  // 4: api.ReplicateChunkRequest
	(*ReplicateChunkResponse)(nil), // 5: api.ReplicateChunkResponse
	(Status)(0),                    // 6: api.Status
}
var file_chunkserver_proto_depIdxs = []int32{
	6, // 0: api.ReadChunkResponse.status:type_name -> api.Status
	6, // 1: api.WriteChunkResponse.status:type_name -> api.Status
	6, // 2: api.ReplicateChunkResponse.status:type_name -> api.Status
	0, // 3: api.ChunkServerService.ReadChunk:input_type -> api.ReadChunkRequest
	2, // 4: api.ChunkServerService.WriteChunk:input_type -> api.WriteChunkRequest
	4, // 5: api.ChunkServerService.ReplicateChunk:input_type -> api.ReplicateChunkRequest
	1, // 6: api.ChunkServerService.ReadChunk:output_type -> api.ReadChunkResponse
	3, // 7: api.ChunkServerService.WriteChunk:output_type -> api.WriteChunkResponse
	5, // 8: api.ChunkServerService.ReplicateChunk:output_type -> api.ReplicateChunkResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_chunkserver_proto_init() }
func file_chunkserver_proto_init() {
	if File_chunkserver_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chunkserver_proto_rawDesc), len(file_chunkserver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chunkserver_proto_goTypes,
		DependencyIndexes: file_chunkserver_proto_depIdxs,
		MessageInfos:      file_chunkserver_proto_msgTypes,
	}.Build()
	File_chunkserver_proto = out.File
	file_chunkserver_proto_goTypes = nil
	file_chunkserver_proto_depIdxs = nil
}
