// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: master.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFileRequest) Reset() {
	*x = CreateFileRequest{}
	mi := &file_master_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileRequest) ProtoMessage() {}

func (x *CreateFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileRequest.ProtoReflect.Descriptor instead.
func (*CreateFileRequest) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{0}
}

func (x *CreateFileRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type CreateFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=api.Status" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFileResponse) Reset() {
	*x = CreateFileResponse{}
	mi := &file_master_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileResponse) ProtoMessage() {}

func (x *CreateFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileResponse.ProtoReflect.Descriptor instead.
func (*CreateFileResponse) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFileResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OK
}

func (x *CreateFileResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type AllocateChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateChunkRequest) Reset() {
	*x = AllocateChunkRequest{}
	mi := &file_master_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateChunkRequest) ProtoMessage() {}

func (x *AllocateChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateChunkRequest.ProtoReflect.Descriptor instead.
func (*AllocateChunkRequest) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{2}
}

func (x *AllocateChunkRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type AllocateChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=api.Status" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ChunkId       string                 `protobuf:"bytes,3,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Chunkservers  []*ChunkServer         `protobuf:"bytes,4,rep,name=chunkservers,proto3" json:"chunkservers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateChunkResponse) Reset() {
	*x = AllocateChunkResponse{}
	mi := &file_master_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateChunkResponse) ProtoMessage() {}

func (x *AllocateChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateChunkResponse.ProtoReflect.Descriptor instead.
func (*AllocateChunkResponse) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{3}
}

func (x *AllocateChunkResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OK
}

func (x *AllocateChunkResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *AllocateChunkResponse) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *AllocateChunkResponse) GetChunkservers() []*ChunkServer {
	if x != nil {
		return x.Chunkservers
	}
	return nil
}

type GetChunkLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	ChunkIndex    int32                  `protobuf:"varint,2,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChunkLocationRequest) Reset() {
	*x = GetChunkLocationRequest{}
	mi := &file_master_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChunkLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChunkLocationRequest) ProtoMessage() {}

func (x *GetChunkLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChunkLocationRequest.ProtoReflect.Descriptor instead.
func (*GetChunkLocationRequest) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{4}
}

func (x *GetChunkLocationRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *GetChunkLocationRequest) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

type GetChunkLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=api.Status" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ChunkId       string                 `protobuf:"bytes,3,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Chunkservers  []*ChunkServer         `protobuf:"bytes,4,rep,name=chunkservers,proto3" json:"chunkservers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChunkLocationResponse) Reset() {
	*x = GetChunkLocationResponse{}
	mi := &file_master_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChunkLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChunkLocationResponse) ProtoMessage() {}

func (x *GetChunkLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChunkLocationResponse.ProtoReflect.Descriptor instead.
func (*GetChunkLocationResponse) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{5}
}

func (x *GetChunkLocationResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OK
}

func (x *GetChunkLocationResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GetChunkLocationResponse) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *GetChunkLocationResponse) GetChunkservers() []*ChunkServer {
	if x != nil {
		return x.Chunkservers
	}
	return nil
}

var File_master_proto protoreflect.FileDescriptor

const file_master_proto_rawDesc = "" +
	"\n" +
	"\fmaster.proto\x12\x03api\x1a\fcommon.proto\"0\n" +
	"\x11CreateFileRequest\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\"^\n" +
	"\x12CreateFileResponse\x12#\n" +
	"\x06status\x18\x01 \x01(\x0e2\v.api.StatusR\x06status\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"3\n" +
	"\x14AllocateChunkRequest\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\"\xb2\x01\n" +
	"\x15AllocateChunkResponse\x12#\n" +
	"\x06status\x18\x01 \x01(\x0e2\v.api.StatusR\x06status\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x19\n" +
	"\bchunk_id\x18\x03 \x01(\tR\achunkId\x124\n" +
	"\fchunkservers\x18\x04 \x03(\v2\x10.api.ChunkServerR\fchunkservers\"W\n" +
	"\x17GetChunkLocationRequest\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x1f\n" +
	"\vchunk_index\x18\x02 \x01(\x05R\n" +
	"chunkIndex\"\xb5\x01\n" +
	"\x18GetChunkLocationResponse\x12#\n" +
	"\x06status\x18\x01 \x01(\x0e2\v.api.StatusR\x06status\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x19\n" +
	"\bchunk_id\x18\x03 \x01(\tR\achunkId\x124\n" +
	"\fchunkservers\x18\x04 \x03(\v2\x10.api.ChunkServerR\fchunkservers2\xe8\x01\n" +
	"\rMasterService\x12=\n" +
	"\n" +
	"CreateFile\x12\x16.api.CreateFileRequest\x1a\x17.api.CreateFileResponse\x12F\n" +
	"\rAllocateChunk\x12\x19.api.AllocateChunkRequest\x1a\x1a.api.AllocateChunkResponse\x12P\n" +
	"\x11GetChunkLocations\x12\x1c.api.GetChunkLocationRequest\x1a\x1d.api.GetChunkLocationResponseB\x1fZ\x1dgithub.com/Yakshith15/GFS/apib\x06proto3"

var (
	file_master_proto_rawDescOnce sync.Once
	file_master_proto_rawDescData []byte
)

func file_master_proto_rawDescGZIP() []byte {
	file_master_proto_rawDescOnce.Do(func() {
		file_master_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_master_proto_rawDesc), len(file_master_proto_rawDesc)))
	})
	return file_master_proto_rawDescData
}

var file_master_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_master_proto_goTypes = []any{
	(*CreateFileRequest)(nil),        // 0: api.CreateFileRequest
	(*CreateFileResponse)(nil),       // 1: api.CreateFileResponse
	(*AllocateChunkRequest)(nil),     // 2: api.AllocateChunkRequest
	(*AllocateChunkResponse)(nil),    // 3: api.AllocateChunkResponse
	(*GetChunkLocationRequest)(nil),  // 4: api.GetChunkLocationRequest
	(*GetChunkLocationResponse)(nil), // 5: api.GetChunkLocationResponse
	(Status)(0),                      // 6: api.Status
	(*ChunkServer)(nil),              // 7: api.ChunkServer
}
var file_master_proto_depIdxs = []int32{
	6, // 0: api.CreateFileResponse.status:type_name -> api.Status
	6, // 1: api.AllocateChunkResponse.status:type_name -> api.Status
	7, // 2: api.AllocateChunkResponse.chunkservers:type_name -> api.ChunkServer
	6, // 3: api.GetChunkLocationResponse.status:type_name -> api.Status
	7, // 4: api.GetChunkLocationResponse.chunkservers:type_name -> api.ChunkServer
	0, // 5: api.MasterService.CreateFile:input_type -> api.CreateFileRequest
	2, // 6: api.MasterService.AllocateChunk:input_type -> api.AllocateChunkRequest
	4, // 7: api.MasterService.GetChunkLocations:input_type -> api.GetChunkLocationRequest
	1, // 8: api.MasterService.CreateFile:output_type -> api.CreateFileResponse
	3, // 9: api.MasterService.AllocateChunk:output_type -> api.AllocateChunkResponse
	5, // 10: api.MasterService.GetChunkLocations:output_type -> api.GetChunkLocationResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_master_proto_init() }
func file_master_proto_init() {
	if File_master_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_master_proto_rawDesc), len(file_master_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_master_proto_goTypes,
		DependencyIndexes: file_master_proto_depIdxs,
		MessageInfos:      file_master_proto_msgTypes,
	}.Build()
	File_master_proto = out.File
	file_master_proto_goTypes = nil
	file_master_proto_depIdxs = nil
}
