syntax = "proto3";

package api;
option go_package = "github.com/Yakshith15/GFS/api";

import "common.proto";

service MasterService {
  rpc CreateFile(CreateFileRequest) returns (CreateFileResponse);
  rpc AllocateChunk(AllocateChunkRequest) returns (AllocateChunkResponse);
  rpc GetChunkLocations(GetChunkLocationRequest) returns (GetChunkLocationResponse);
}


message CreateFileRequest {
  string file_path = 1;
}

message CreateFileResponse {
  Status status = 1;
  string error_message = 2;
}

message AllocateChunkRequest {
  string file_path = 1;
}

message AllocateChunkResponse {
  Status status = 1;
  string error_message = 2;

  string chunk_id = 3;
  repeated ChunkServer chunkservers = 4;
}

message GetChunkLocationRequest {
  string file_path = 1;
  int32 chunk_index = 2;
}

message GetChunkLocationResponse {
  Status status = 1;
  string error_message = 2;

  string chunk_id = 3;
  repeated ChunkServer chunkservers = 4;
}